services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: computer_shop
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: mysql

volumes:
  mysql-data:
